### ISSUE TITLE
TODO 需求跟进

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#1653]
### 1.1 蓝盾对接

- [x] 接入支持
- [x] 蓝盾数据迁移

### 1.2 页面模型接入

- [x] [[RBAC] model api支持注册屏蔽功能](https://github.com/TencentBlueKing/bk-iam-saas/issues/1107)
- [ ] [[API] 模型变更 API](https://github.com/TencentBlueKing/bk-iam-saas/issues/576)
- [ ] [[Backend] action支持隐藏/删除](https://github.com/TencentBlueKing/bk-iam-saas/issues/483)
- [x] [[SaaS] 屏蔽Action](https://github.com/TencentBlueKing/bk-iam-saas/issues/406)

### 1.3 审计对接

- [x] [[审计] 权限中心相关需求](https://github.com/TencentBlueKing/bk-iam-saas/issues/1306)

### 1.4 其它

- [ ] [获取分级管理员下所有用户组下的成员（用户、组织）列表](https://github.com/TencentBlueKing/bk-iam-saas/issues/1547)
- [x] [【已评审】支持二级管理空间方案](https://github.com/TencentBlueKing/bk-iam-saas/issues/1528)
- [ ] [自定义权限支持分级管理员审批](https://github.com/TencentBlueKing/bk-iam-saas/issues/1354)
- [ ] [编辑分级管理员单据增加diff](https://github.com/TencentBlueKing/bk-iam-saas/issues/1314)
- [ ] [[Backend] ROLE授权范围同步到iam search engine方案](https://github.com/TencentBlueKing/bk-iam-saas/issues/89)

### 2.1 CI/CD

- [x] [[运维] bkop环境纳管上云版集群及部署切换](https://github.com/TencentBlueKing/bk-iam-saas/issues/1566)
- [ ] [[RBAC] prod环境增加备份机器](https://github.com/TencentBlueKing/bk-iam-saas/issues/1433)
- [x] [[部署] 多渠道对权限中心进行部署](https://github.com/TencentBlueKing/bk-iam-saas/issues/866)
- [ ] [[运维] 发布-回滚或宕机一段时间后重新拉起缓存非最新](https://github.com/TencentBlueKing/bk-iam-saas/issues/568)

### 2.2 高可用

- [ ] [[Backend] 后台redis缓存重新review](https://github.com/TencentBlueKing/bk-iam-saas/issues/1559)
- [x] [[Backend] 容器化migrate错误处理](https://github.com/TencentBlueKing/bk-iam-saas/issues/1557)
- [ ] [[SDK] client 端可用性提升](https://github.com/TencentBlueKing/bk-iam-saas/issues/1572)
- [ ] [[Backend] 数据库与缓存的数据一致性优化](https://github.com/TencentBlueKing/bk-iam-saas/issues/598)

### 3.1 高优先级

- [x] [确定单测优先级, 拆分issue](https://github.com/TencentBlueKing/bk-iam-saas/issues/1650)
- [x] [[Backend] 升级并测试gin最新版本](https://github.com/TencentBlueKing/bk-iam-saas/issues/1153)
- [x] [[SaaS] celery版本升级 5.2.x](https://github.com/TencentBlueKing/bk-iam-saas/issues/718)
- [x] [[SaaS] Redis配置支持哨兵和单机模式](https://github.com/TencentBlueKing/bk-iam-saas/issues/586)
- [x] [[SaaS] 升级核心依赖第三方包](https://github.com/TencentBlueKing/bk-iam-saas/issues/480)
- [x] [[SaaS] 升级django 3.2.x](https://github.com/TencentBlueKing/bk-iam-saas/issues/479)
- [x] [[SaaS] 用户组/权限模板/分级管理员的名称唯一性添加](https://github.com/TencentBlueKing/bk-iam-saas/issues/204)
- [x] [[SaaS] Policy授权关键链路增加强校验](https://github.com/TencentBlueKing/bk-iam-saas/issues/186)
- [x] [[Backend] sql 慢查询分析及优化](https://github.com/TencentBlueKing/bk-iam-saas/issues/140)

### 3.2 低优先级

- [ ] [[SaaS] 查询可申请的用户组列表优化](https://github.com/TencentBlueKing/bk-iam-saas/issues/1321)
- [ ] [[Debug] 提供RBAC同步检查数据的debug api, 同时更新debug cli](https://github.com/TencentBlueKing/bk-iam-saas/issues/1311)
- [ ] [[SaaS] API待性能优化汇总](https://github.com/TencentBlueKing/bk-iam-saas/issues/1004)
- [ ] [[SaaS] OpenAPI性能优化 - 审计日志保存](https://github.com/TencentBlueKing/bk-iam-saas/issues/982)
- [ ] [[SaaS] 组织架构同步的测试](https://github.com/TencentBlueKing/bk-iam-saas/issues/821)
- [ ] [[评估] SaaS侧存储的大表](https://github.com/TencentBlueKing/bk-iam-saas/issues/1147)
- [ ] [[讨论] 接入系统资源删除后, 如何标记并回收策略](https://github.com/TencentBlueKing/bk-iam-saas/issues/629)
- [ ] [[SaaS] DB Migration初始化解耦依赖外部API和内置白名单](https://github.com/TencentBlueKing/bk-iam-saas/issues/587)
- [x] [[SaaS] 对外提供的查询类OpenAPI考虑添加缓存](https://github.com/TencentBlueKing/bk-iam-saas/issues/190)
- [ ] [[Backend] SaaS调用IAM Backed接口分析优化](https://github.com/TencentBlueKing/bk-iam-saas/issues/706)
- [ ] [[SaaS] OpenAPI添加业务Metrics指标](https://github.com/TencentBlueKing/bk-iam-saas/issues/853)

**Comment by zhu327** [comment]
1. 管理类api查询用户组列表增加描述筛选
2. 新增自定义权限申请单创建api, 返回sn
3. 降低日志级别, 打warn日志 https://github.com/TencentBlueKing/bk-iam-saas/blob/master/saas/backend/account/backends.py#L127

**Comment by zhu327** [comment]
优先处理事项:

- [ ] [[上云版] RBAC 发布后, 生产环境配置告警](https://github.com/TencentBlueKing/bk-iam-saas/issues/1442)
- [ ] [[SaaS] 接入系统回调接口返回数据校验 ](https://github.com/TencentBlueKing/bk-iam-saas/issues/1678)
- [ ] [[审计中心] 注册 resource_type&action 时，sensitivity不生效](https://github.com/TencentBlueKing/bk-iam-saas/issues/1670)
- [ ] [[蓝盾] 资源回收清理相关数据](https://github.com/TencentBlueKing/bk-iam-saas/issues/1657)
- [ ] [[SaaS] 白名单从migration中剥离](https://github.com/TencentBlueKing/bk-iam-saas/issues/1474)
- [ ] [代码库剥离version/release.md等](https://github.com/TencentBlueKing/bk-iam-saas/issues/1457)
- [ ] [[SaaS] DB Migration初始化解耦依赖外部API和内置白名单](https://github.com/TencentBlueKing/bk-iam-saas/issues/587)
- [ ] [[SaaS] XList 内聚性重新评估](https://github.com/TencentBlueKing/bk-iam-saas/issues/377)
- [ ] [[SaaS] List[X] 与 XLIst优化](https://github.com/TencentBlueKing/bk-iam-saas/issues/375)
- [ ] [[SaaS] 代码优化项](https://github.com/TencentBlueKing/bk-iam-saas/issues/362)
- [ ] [[SaaS] 长时任务增加/metrics](https://github.com/TencentBlueKing/bk-iam-saas/issues/360)
