### ISSUE TITLE
【规划】2023年H1规划

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#1711]
https://github.com/TencentBlueKing/bk-iam-saas/issues/1192

---

review下, 下半年的需求做的不多

**Comment by zhu327** [comment]
需求:

- #1720
- #1713
- #1708
- #1696
- #1681
- #1680
- #1642
- #1635
- #1610
- #1609
- #1608 
- #1606
- #1565 
- #1561 
- #1548
- #1547 
- #1546 
- #1545 
- #1544 
- #1543 
- #1528 
- #1516 
- #1484 
- #1435 
- #1422 
- #1364 
- #1360
- #1354 
- #1318 
- #1308
- #1302 
- #1276 
- #1178 
- #1170 
- #1164 
- #1157 
- #1118
- #1114 
- #1100 

前端:

- #1654
- #1636 
-

**Comment by zhu327** [comment]
产品:

https://github.com/TencentBlueKing/bk-iam-saas/issues?page=1&q=is%3Aopen+assignee%3AXmandon

**Comment by zhu327** [comment]
前端:

https://github.com/TencentBlueKing/bk-iam-saas/issues?q=is%3Aopen+assignee%3Ahuangpeng0428

**Comment by zhu327** [comment]
后台:

- [ ] [[上云版] RBAC 发布后, 生产环境配置告警](https://github.com/TencentBlueKing/bk-iam-saas/issues/1442)
- [ ] [[SaaS] 接入系统回调接口返回数据校验 ](https://github.com/TencentBlueKing/bk-iam-saas/issues/1678)
- [ ] [[审计中心] 注册 resource_type&action 时，sensitivity不生效](https://github.com/TencentBlueKing/bk-iam-saas/issues/1670)
- [ ] [[蓝盾] 资源回收清理相关数据](https://github.com/TencentBlueKing/bk-iam-saas/issues/1657)
- [ ] [[SaaS] 白名单从migration中剥离](https://github.com/TencentBlueKing/bk-iam-saas/issues/1474)
- [ ] [代码库剥离version/release.md等](https://github.com/TencentBlueKing/bk-iam-saas/issues/1457)
- [ ] [[SaaS] DB Migration初始化解耦依赖外部API和内置白名单](https://github.com/TencentBlueKing/bk-iam-saas/issues/587)
- [ ] [[SaaS] XList 内聚性重新评估](https://github.com/TencentBlueKing/bk-iam-saas/issues/377)
- [ ] [[SaaS] List[X] 与 XLIst优化](https://github.com/TencentBlueKing/bk-iam-saas/issues/375)
- [ ] [[SaaS] 代码优化项](https://github.com/TencentBlueKing/bk-iam-saas/issues/362)
- [ ] [[SaaS] 长时任务增加/metrics](https://github.com/TencentBlueKing/bk-iam-saas/issues/360)
