### ISSUE TITLE
[讨论] 如何进一步降低接入成本

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#18]
## 降低接入成本

有哪些方面可以推广? 有哪些思路

**Comment by wklken** [comment]
## 文档

- [ ] 补充所有 [蓝鲸开源项目](https://github.com/TencentBlueKing) 中使用权限中心的例子汇总到接入样例
- [ ] 补充: 多种模型注册的方式说明  API 注册/do_migrate.py/iam-python-sdk migration   #47 
- [ ] 优化IAM_HOST #56 
- [ ] 统一调用方式为 APIGateway #46 
- [ ] 补充 _bk_iam_path_详细说明 #45 
- [ ] 增加concepts所有概念说明  #27 
- [ ] 精简/突出重点/脉络  #33 
- [ ] 重新梳理每个文档的详细描述, 确保容易理解/无歧义/精简
- [ ] 增加设计原理  #26 
- [ ] how to benchmark #25 
- [ ] python sdk文档优化
- [ ] go sdk文档优化

## 统一使用 APIGateway 调用

- [ ]  Python SDK支持 APIGateway
- [ ] Go SDK 支持 APIGateway 
- [ ] [APIGateway] 容器化版本需要自动注册所有网关到 APIGateway #57
- [ ] 推动内部版/蓝鲸所有产品切换
- [ ] 外发, 变更官网文档

**Comment by wklken** [comment]
move plan to: https://github.com/TencentBlueKing/bk-iam-saas/issues/65
