### ISSUE TITLE
2021-09-27 需求盘点

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#197]
# 剩余需求盘点:

## 来自于接入系统:

- [x] 蓝盾: 实例审批人, 项目审批人   90%,  预计 28日发
- [ ] 蓝盾: 申请审批查询分级管理员        方案调研中   #89    @zhu327 
- [x] Fit: 某个项目切换v3                   doing, 预计 今日完成
- [x] Fit: 流水线页面管权限, 需走蓝盾接口调用权限中心       需要考虑限制, 另外实例级别接口授权, 超过限制的风险很大                [风险高, 需谨慎]   @nannan00 
- [x] bf: 笛卡尔积      暂无结论  #194
- [x] bf: 实例有效期   暂无结论    #106 
- [ ] 支持接入系统内管理资源实例权限 #188    暂时不处理
- [x] 嘉为 - 像tea可以管理多个系统(白名单等)/创建组(说明风险)/组加减人/组自定义权限

## 原先规划:
- [ ] RBAC 方案
- [ ] 环境属性
- [ ] 页面接入二期     10月 8 日之后开始
- [ ] 推动内外部版切换使用APIGateway(最好的时机是容器化版本成熟)
- [ ] auth 服务

## 其他:
- [x] 容器化SaaS支持helm, 走统一规范   #195 
- [x] 新版表达式变更  #177  #135
- [x] API 自动注册到APIGateway
- [ ] 实例过多 配置权限页面的性能问题(包括deepcopy)

## 协作开发:

- [ ]  长时任务展示 #199
- [x] 组织架构同步记录展示 #200
- [ ] 管理后台一期-白名单及屏蔽 #201

**Comment by zhu327** [comment]
可以考虑让嘉为同学参与的需求:

1. 权限中心管理后台, 由我们这边设计/把关, 由嘉为同学实现

**Comment by wklken** [comment]
协作开发: 
- 长时任务的展示
- 组织架构同步记录的展示
- 管理后台一期
