### ISSUE TITLE
[SaaS]高优先级事项

### ISSUE THREAD

**Issue by Xmandon** [TencentBlueKing/bk-iam-saas#273]
问题：
- [x]  分级管理员编辑同步模板（解决模板授权报错问题） #270 
- [x]  合并选择针对空资源实例操作的处理 `进度：已沟通，使用问题，批量粘贴满足场景`
- [x]  模板授权经常出现“有用户组正在授权，禁止提交新的更新任务” 
- [x]  (交付时间：11.25) 资源实例名称变更/删除处理，优先解决实例（业务）名变更导致分级管理员无法授权问题。`进度：已交付`https://github.com/TencentBlueKing/bk-iam-saas/issues/311

需求：
- [x]  (交付时间：) 去笛卡尔积方案处理（其他需求的前置条件）。`进度：本周前后端联调`
- [x]  (交付时间：12.20) 审计需求（基于实例的权限管理），导出   -协作开发 `进度：已沟通，先实现页面查询功能满足需求，开发实现中` @wklken  跟进 https://github.com/TencentBlueKing/bk-iam-saas/issues/275 
- [x]  (交付时间：12.10) 权限交接   -协作开发 `进度：前端本周开发` https://github.com/TencentBlueKing/bk-iam-saas/issues/302
- [x]  (交付时间：1.14)分钟级授权/环境属性（时间范围需求）`进度：已沟通，先实现生效条件满足需求，开发实现中`https://github.com/TencentBlueKing/bk-iam-saas/issues/385

**Comment by Xmandon** [comment]
审计需求结论：
1. 操作维度：自己调用policylist接口查询到一个系统某个操作下的所有策略列表，没有去重，里面有用户、用户组信息，过期时间是实时的
2. 实例维度：遍历用户+操作+实例，走鉴权接口，风险点：实例、用户量很大的时候比较慢

**Comment by wklken** [comment]
policy list: https://bk.tencent.com/docs/document/6.0/160/8454
鉴权接口: 走sdk鉴权或 API 鉴权 https://bk.tencent.com/docs/document/6.0/160/8457   /  https://bk.tencent.com/docs/document/6.0/160/8456
