### ISSUE TITLE
[SaaS] 代码优化项

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#362]
SaaS 层Python代码需要做优化

> 升级; 使用新特性; 切换外部依赖; 减少整体维护代码量

## 优先级高

- [x] 升级 pydantic #537 
- [x] ErrorCode替换 - 使用blue-krill   #54 
- [x] 去除目录blueapps&blueking #536
- [x] 升级django 3.2.x [重要, 现在可以做] https://docs.djangoproject.com/en/3.2/releases/
- [x] 分布式锁 lock 重构 => 统一抽象, 统一实现, 统一的引用 #565
- [ ] 使用高性能的json库(orjson只支持python3.7及以上)
- [ ] 优化deepcopy逻辑 (减少次数 / 有没有别的路子 json.loads(json.dumps()))
- [x] 升级: requests / pydantic / djangorestframework / mysql / redis 等核心依赖包

## 其他

- [ ] 使用blue_krill.editions 管理多版本
- [ ] healthz 切换使用 [blue-krill](https://github.com/TencentBlueKing/bkpaas-python-sdk/blob/master/sdks/blue-krill/README.md#7-blue_krillmonitoringprobe)

- [ ] 升级python版本? (未来, 不支持v2版本后)
- [x] 现在存在大量的重复slz? 
- [ ] 上层biz/handler存在部分对象作为参数的typhint丢了
- [ ] service层的 ActionList 与 List[Action]
- [x] 命名优化: ResourceTypeService . `list_resource_type_by_systems`/`get_resource_type_dict`
- [x] VerifyAPIParamLocationEnum rename to VerifyApiParamLocationEnum 
- [x] backend/api/mixins.py => verify_system_client 有优化的空间吗?
- [x] 不一致的命名: backend/service/constants.py 有等
- [ ] 重复代码
    - lines 70-79 from saas/backend/api/admin/views/group.p
    - lines 229-238 from saas/backend/api/management/views/group.py
- [x] 重复代码
    - lines 52-61 from resource.py
    - lines 97-106 from resource.py
- [x] 重复代码
    - lines 68-80 from resource_creator_action.py
    - lines 120-132 from resource_creator_action.py

- [ ] pydantic指定某些model初始化后不可变  `allow_mutation`
- [ ] pydantic重要模型字段需要有必要的校验
- [x]  Log配置(celery日志在文件里存在，但日志格式与开发者中心解析规则不一致，导致开发者中心查询不到)

**Comment by zhu327** [comment]
重新review下

**Comment by zhu327** [comment]
https://github.com/TencentBlueKing/bk-iam-saas/issues/377
https://github.com/TencentBlueKing/bk-iam-saas/issues/375

一同处理
