### ISSUE TITLE
[规划] 降低接入成本

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#65]
## 1. 接入页面

> 后续模型的构建/示例说明/图文等, 以接入页面为主

- [ ] 接入页面二期  #12 
- [ ] 接入示例作为默认的可见`接入页面系统`; 接入示例作为默认应用部署;

## 2. 文档

- [ ] 补充所有 [蓝鲸开源项目](https://github.com/TencentBlueKing) 中使用权限中心的例子汇总到接入样例
- [ ] 补充: 多种模型注册的方式说明  API 注册/do_migrate.py/iam-python-sdk migration   #47 
- [ ] 优化IAM_HOST #56 
- [ ] 统一调用方式为 APIGateway #46 
- [ ] 补充 _bk_iam_path_详细说明 #45 
- [ ] 增加concepts所有概念说明  #27 
- [ ] 精简/突出重点/脉络 (现在的问题是太多了)  #33 
    - 哪些是接入系统需要做的? (构建模型/注册模型/鉴权), 哪些是了解就好的? (现在似乎没有重点)
- [ ] 重新梳理每个文档的详细描述, 确保容易理解/无歧义/精简
- [ ] 增加设计原理  #26 
- [ ] how to benchmark #25 
- [ ] python sdk文档优化
- [ ] go sdk文档优化
- [ ] 问题: **还需要补充哪些接入样例**?
- [ ] 丰富完善 FAQ, 并主推: 产品侧/概念侧的问答, 例如 什么是实例视图?  怎么注册模型? (需要收集一波)
- [ ] 问题排查文档优化, 做好分类及指引(目前有点杂)

## 3. 统一使用 APIGateway 调用

- [ ]  Python SDK支持 APIGateway
- [ ] Go SDK 支持 APIGateway 
- [ ] [APIGateway] 容器化版本需要自动注册所有网关到 APIGateway #57
- [ ] 推动内部版/蓝鲸所有产品切换
- [ ] 外发, 变更官网文档

## 4. SDK

- [ ]  Java SDK 开源(重要) #31 
- [ ]  开发并开源 PHP SDK(需要寻求开发者)  #21 
- [ ] 开发并开源 Javascript SDK需要寻求开发者)  #19 
- [ ] 开发并开源 Ruby SDK (优先级相对低) #22 

## 5. 课程&视频教程

问题: 现有产品/接入的视频之外, 还需要提供哪些课程?视频教程?

**Comment by wklken** [comment]
- [ ] #387
- [ ] #388
