### ISSUE TITLE
Milestone: 2022M10

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#831]
## 产品

关键目标:

事项:

- [ ] 1. RBAC产品形态确认 https://github.com/TencentBlueKing/bk-iam-saas/issues/17
- [ ] 2. 监控可观测性产品功能项梳理https://github.com/TencentBlueKing/bk-iam-saas/issues/805
- [x] 3. 分级管理员级联方案评估 https://github.com/TencentBlueKing/bk-iam-saas/issues/835

## 前端
关键目标:
临时权限页面功能开发

- [ ] #832
- [x] #833

事项: 

## 后台

[SaaS]

临时权限

- [x] #799 
- [x] #798 
- [x] #797 

SaaS Open API

- [x] #773 
- [x] #619 
- [ ] #309 
- [ ] #397 
- [ ] #574 
- [ ] #836 

协作开发

- [ ] #713 
- [ ] #750 

其它
- [ ] #772
