### ISSUE TITLE
Milestone: 2022M11

### ISSUE THREAD

**Issue by wklken** [TencentBlueKing/bk-iam-saas#849]
## 产品

关键目标:
- [ ] 1. 蓝盾权限对接优化设计确认 https://github.com/TencentBlueKing/bk-iam-saas/issues/620
- [x] 2. 监控可观测性产品功能项梳理https://github.com/TencentBlueKing/bk-iam-saas/issues/805
- [ ] 3. 后台管理框架设计稿输出 https://github.com/TencentBlueKing/bk-iam-saas/issues/686

- [x] 4. 产品文档刷新

事项:

讨论：

- [ ]  基于token授权管理需求（bcs需求）

## 前端
关键目标:
完成临时权限功能
处理协作开发的事项

- [x] #832

## 后台

关键目标:
- RBAC方案
- OpenAPI优化

事项: 

[Open API]
- [ ] #851
  - [x] #53
  - [x] #548
  - [x] #397
  - [ ] #574
  - [ ] #620
- [ ] 新增API
  - [ ] #309
  - [ ] #836

[RBAC]
- [ ] #245 
- [ ] #699 

协作开发

- [ ] #713 
- [ ] #750 

其它
- [ ] #809 
- [x] #772
