### ISSUE TITLE
[方案] RBAC实现

### ISSUE THREAD

**Issue by zhu327** [TencentBlueKing/bk-iam-saas#913]
#245 

按现有的结论做实现方案的可行分析, 包括以下重点:

- 对现有的权限模型的冲击
- api的设计(是否需要独立的api)
- 详细的表结构与查询, 插入SQL语句
- cache的实现设计

**Comment by zhu327** [comment]
1. 提供鉴权/批量鉴权api

```json
{
	"system": "bk_job",
	"subject": {
		"type": "user",
		"id": "admin"
	},
	"action": {
		"id": "execute"
	},
	"resources": [{   // 资源类型的顺序必须操作注册时的顺序一致, 否则会导致鉴权失败!
		"system": "bk_job",
		"type": "job",
		"id": "ping"
	}, {
		"system": "bk_cmdb",
		"type": "host",
		"id": "192.168.1.1",
	}]
}
```

**Comment by zhu327** [comment]
```sql
/*
rbac 相关表结构, 是否需要加上前缀
*/
CREATE TABLE `group` (
  `pk` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `system_id` varchar(32) NOT NULL,
  `id` varchar(64) NOT NULL,
  `name` varchar(64) NOT NULL DEFAULT '',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `subject_group` (
  `pk` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `system_id` varchar(32) NOT NULL,
  `subject_pk` int(10) unsigned NOT NULL,
  `subject_type` varchar(16) NOT NULL,
  `subject_id` varchar(64) NOT NULL,
  `group_pk` int(10) unsigned NOT NULL,
  `group_id` varchar(64) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `group_resource_policy` (
  `pk` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `system_id` varchar(32) NOT NULL,
  `resource_type_uniq_id` varchar(64) NOT NULL,
  `group_pk` int(10) unsigned NOT NULL,
  `action_ids` TEXT NOT NULL,  /* JSON */
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='policy with resource';

CREATE TABLE `group_no_resource_policy` (
  `pk` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `system_id` varchar(32) NOT NULL,
  `action_pk` varchar(32) NOT NULL,
  `group_pk` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='policy without resource';

/*
关联任意资源类型的权限
*/
CREATE TABLE `group_any_resource_policy` (
  `pk` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `system_id` varchar(32) NOT NULL,
  `action_pk` varchar(32) NOT NULL,
  `group_pk` int(10) unsigned NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pk`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='policy with any resource';

/*
group继承关系表, 主要关注 group_pk 与 parent_pk, 其它字段都是为了构建mptt
*/
CREATE TABLE `group_relation` (
  `pk` int(10) unsigned NOT NULL,
  `system_id` varchar(32) NOT NULL,
  `group_pk` int(10) unsigned NOT NULL,
  `parent_pk` int(11) DEFAULT NULL,

  `lft` int(10) unsigned NOT NULL,
  `rght` int(10) unsigned NOT NULL,
  `tree_id` int(10) unsigned NOT NULL,
  `level` int(10) unsigned NOT NULL,

  `created_time` datetime(6) NOT NULL,
  `updated_time` datetime(6) NOT NULL,
  PRIMARY KEY (`pk`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by zhu327** [comment]
### 鉴权逻辑

#### 1. 操作关联资源类型

```json
{
	// "system": "bk_job", 迁移到url path中
	"subject": {
		"type": "user",
		"id": "admin"
	},
	"action": {
		"id": "execute"
	},
	"resource": { 
		"system": "bk_job",
		"type": "job",
		"id": "ping"
	}
}
```

1. 根据resource查询group_resource_policy表，查询出所有的group_pk, action_ids

```sql
SELECT group_pk, action_ids FROM group_resource_policy WHERE system_id = 'bk_job' AND resource_type_uniq_id = 'job:ping';
```

2. 根据action_id筛选出action_ids中包含的action_id的group_pk

3. 查询subject_group表，匹配是否存在以上group_pk与subject_pk的记录

```sql
SELECT COUNT(*) FROM subject_group WHERE group_pk IN (?) AND subject_pk = ? AND system_id = 'bk_job';
```

注: 

- 后续要实现操作关联任意资源类型, 需要增加group_any_resource_policy表的查询步骤

```sql
SELECT group_pk FROM group_any_resource_policy WHERE system_id = 'bk_job' AND action_pk = ?;
```

- 后续要实现RBAC1, 需要增加group_pks查询`group_relation`表所有祖先步骤

#### 2. 操作不关联资源类型

```json
{
	// "system": "bk_job", 迁移到url path中
	"subject": {
		"type": "user",
		"id": "admin"
	},
	"action": {
		"id": "execute"
	},
	"resource": {}
}
```

1. 查询出所有的group_pk

```sql
SELECT group_pk FROM group_no_resource_policy WHERE system_id = 'bk_job' AND action_pk = ?;
```

2. 查询subject_group表，匹配是否存在以上group_pk与subject_pk的记录

```sql
SELECT COUNT(*) FROM subject_group WHERE group_pk IN (?) AND subject_pk = ? AND system_id = 'bk_job';
```

**Comment by zhu327** [comment]
### 鉴权前置过程

1. 查询subject的pk
2. 查询action的pk

以上subject_pk与action_pk都在主程序的数据库中, 所以需要针对分布式实例要配置共享的模型/subject的数据库

**Comment by zhu327** [comment]
### TODO

1. 批量鉴权
2. rbac_subject_group 是否能通过 bitmap 做优化
3. group写入相关逻辑

**Comment by wklken** [comment]
- [ ] - rbac_group.name   default '' ?
- [ ] - rbac_subject_group.group_id 不需要冗余吧? 
- [ ]     - rbac_subject_group 的索引, subject_pk/system_id是确定的, group_pk是in, 索引group_pk在中间, 是否能命中? 
- [ ] - rbac_group_resource_policy  resource_type_uniq_id 有没有更好的名字? reousrce_uniq_id?
- [ ] - rbac_group_no_resource_policy 的索引,  除了 action_pk, system_id 加上 group_pk?   => 避免回源表拿数据
- [ ] - rbac_group_any_resource_policy 同上?   => 避免回源表拿数据
- [ ] - 其他: rbac_group_any_resource_policy 的action_pk一定是要关联资源类型的; 非关联资源类型的不能出现在这个表 (这个在代码逻辑上需要做限制, 即前置检查)
- [ ] - 其他: 是否需要加入last_access_at timestamp?  未来清理

-------------

- [ ] - `SELECT COUNT(*) FROM rbac_subject_group`  使用 `limit 1` 或 `exists`测试下性能? 一旦匹配停止计算
- [ ] - 鉴权逻辑, resource需要是一个列表? 还是实现类似, 单个resource是{}, 多个resource是resource_list[] 这里协议需要好好思考下
- [ ] - rbac_subject_group 如果不能优化, 需要cache一个  subject_pk => groups的独立redis Cache;(用字符串或列表)

-------------

需要补充其他场景:
1. 查询组列表/组详情
2. 查询组成员列表
3. 通过资源查询其关联组列表

**Comment by nannan00** [comment]
1. rbac_subject_group表索引 (`subject_pk`,`group_pk`,`system_id`) 是否不太合适，需要测试一下 where subject_pk = ? AND group_pk in (?) AND system_id=? 的索引是否命中

2. 对于1.3里的count(*) ，性能应该没有limit 1或 exists高


补充：
1. 补充支持配置了部门加入用户组后，对subject=user的整个鉴权都需要添加哪些查询或计算
1. 缓存方案，不同缓存实现会导致SQL查询的变化

**Comment by zhu327** [comment]
1. 通过资源实例查询group列表
2. 通过资源实例、action_id查询有权限的组

**Comment by zhu327** [comment]
### group授权给部门鉴权逻辑

1. 通过subject_pk回溯subject所有的部分的subject_pks
2. 鉴权第三步修改为

```sql
SELECT COUNT(*) FROM rbac_subject_group WHERE group_pk IN (?) AND subject_pk IN (?) AND system_id = 'bk_job';
```

**Comment by zhu327** [comment]
- [ ] 单系统的用户组实现 ABAC

**Comment by zhu327** [comment]
- [ ] rbac_group_resource_policy 通过资源实例查询出来后要能做到快速筛选 action
- [ ] rbac_subject_group 匹配subject是否在group中时, 需要有缓存的设计

**Comment by zhu327** [comment]
### RBAC讨论记录

TODO:

1. SaaS Policy如何拆分成RBAC/ABAC不同的数据? @jiananzhang
   - 综合考虑SaaS权限的变更相关逻辑, 包括web/open api
2. Group在授权时如何区分出是RBAC/ABAC, 怎样对Subject-Group的关系打标签 @tianyizhu
3. Subject-Relation表怎么做到系统维度的隔离, subject查询出相关的group列表怎么做到压缩存储 @tianyizhu
   - subject-system-groups CURD逻辑处理, 缓存设计
   - 评估每个subject最多能关联多少个RBAC用户组
4. subject-relation 精简字段 @tianyizhu
5. SaaS policy表字段压缩/分表 @jiananzhang

---

结论:

1. 蓝盾的资源实例被删除时需要同步删除资源关联的RBAC用户组
2. 每个资源实例最多能创建RBAC用户组的数量10个 -- 压测评估最大数量
3. ABAC中每个subject每个系统最多能关联100个用户组 -- 压测评估最大数量

@edwinwu

补充问题:

1. 没有授权的用户组的 subject-group 关系只存在 subject-relation 表中
2. 用户组在授权时, 关系写入 subject-system-groups 表中
   - 存在问题如果有ABAC/RBAC的数量限制, 这个时候在授权时拒绝吗?

**Comment by zhu327** [comment]
产品相关的点:
1. 人 - 组的有效期是否去掉? 
2. ignore_path的默认值是否改成True?
3. 蓝盾这类系统(只使用实例授权的), 鉴权必须传递所有资源(这个是限制, 必须的)
4. 蓝盾这类系统, 删除资源必须调用回收接口, 回收组/权限
5. 每个资源最多能关联多少个用户组(角色)? 10 个?

**Comment by zhu327** [comment]
限制：

1. 接入系统鉴权时，需要给到request.resource信息(包括_bk_iam_path_)，否则无法鉴权RBAC权限 , SDK 批量获取策略如何实现？

2.  默认配置ignore_path = True ?

**Comment by Xmandon** [comment]
job现有的ignore_path的实现不能受影响

**Comment by zhu327** [comment]
1. 确定策略走RBAC分支逻辑的条件

**Comment by zhu327** [comment]
1. redis的快速查询 group auth_type 
2. 其它的数据结构能快速索引出group的auth_type

**Comment by zhu327** [comment]
结构:

key: group_pk int
value: auth_type int

**Comment by zhu327** [comment]
本地缓存 + changlist

**Comment by zhu327** [comment]
system: str
group_pk: int
auth_type: int

---

redis

key: system + auth_type
value: group_pk set

问题:

system auth_type 变更时怎么处理?

1. 从一个set中删除(如果需要)
2. 新增到另一个set/或者新增到另外2个set

如何获取比较?

1. 从redis中全读出来, 数据量不好控制
2. 直接使用redis的方法取交集, subject + system groups 与 system group set的数量都不好控制

如何从数据库中查询?

1. key不存在, 从数据库中查询
2. 怎样保证数据库与redis的数据强一致??? 不可靠

---

本地缓存

key: system + group_pk
value: auth_type

redis changlist

changlist只存group_pk, timestamp, 不区分system, 查询过程中只要有group_pk有变更, 直接丢弃

不做多级缓存, 只保存在本地缓存中

---

**Comment by zhu327** [comment]
etcd/boltdb 底层使用文件存储, 不适合多实例同时写

**Comment by zhu327** [comment]
问题:

1. 怎么查询有权限的用户组

相关功能:

1. 无权限跳转申请推荐用户组
2. 超级管理员资源管理
